version: '2'

services:
  client:
    build: worker
    links:
      - server
    volumes:
      - ${PWD}:/host
      - /tmp  # workaround "File name too long" errors when extracting some jars
    working_dir: /host
    privileged: true
