version: '2'

services:
  server:
    build: server
    command: bash -c "/usr/bin/nellie-server && sleep infinity"
    hostname: quickstart.cloudera
    container_name: quickstart.cloudera
    privileged: true
    expose:
      - "80"     # tutorial
      - "8020"   # hdfs
      - "8032"   # yarn
      - "8042"   # container logs
      - "8088"   # jobtracker
      - "10020"  # jobhistory IPC
      - "19888"  # jobhistory
      - "50070"  # hdfs status

    # The following settings are required to support 'exec', which is only a temporary workaround.
    volumes:
      - ${PWD}:/host
      - /tmp  # workaround "File name too long" errors when extracting some jars
    working_dir: /host

  worker:
    build: worker
    links:
      - server
    command: bash -c "/usr/bin/nellie-worker && sleep infinity"

  webproxy:
    image: paintedfox/tinyproxy:latest
    links:
      - server
    ports:
      - "8888"  # ideally we should only bind to the host IP, but we can't inspect that

  client:
    build: worker
    links:
      - server
    volumes:
      - ${PWD}:/host
      - /tmp  # workaround "File name too long" errors when extracting some jars
    working_dir: /host
    privileged: true
