version: '2'

services:
  server:
    build: server
    command: bash -c "/usr/bin/nellie-server && sleep infinity"
    hostname: quickstart.cloudera
    container_name: quickstart.cloudera
    privileged: true
    expose:
      - "80"     # tutorial
      - "8020"   # hdfs
      - "8032"   # yarn
      - "8088"   # jobtracker
      - "19888"  # jobhistory
      - "50070"  # hdfs status

  worker:
    build: worker
    links:
      - server
    command: bash -c "/usr/bin/nellie-worker && sleep infinity"

  webproxy:
    #image: paintedfox/tinyproxy:1.8.3
    build: worker
    command: sleep infinity
    ports:
      - "127.0.0.1::8888"