version: '2'

services:
  server:
    build: server
    command: bash -c "/usr/bin/nellie-server && sleep infinity"
    hostname: quickstart.cloudera
    container_name: quickstart.cloudera
    privileged: true
    ports:
      - "50070:50070"  # hdfs status
      - "8088:8088"    # jobtracker
      - "19888:19888"  # jobhistory

    expose:
      - "8020"  # hdfs
      - "8032"  # yarn

  worker:
    build: worker
    links:
      - server
    command: bash -c "/usr/bin/nellie-worker && sleep infinity"
