#! /usr/bin/env bash

DAEMONS="\
    mysqld \
    cloudera-quickstart-init \
    zookeeper-server \
    hadoop-hdfs-journalnode \
    hadoop-hdfs-namenode \
    hadoop-hdfs-secondarynamenode \
    hadoop-mapreduce-historyserver \
    hadoop-yarn-resourcemanager \
"

# Run datanode here too, in order to preserve the data that exists
# on HDFS (mainly oozie support files). The worker nodes, although
# based on the same docker image, have had this data deliberately wiped.
DAEMONS="${DAEMONS} \
    hadoop-hdfs-datanode \
    hadoop-yarn-nodemanager \
"

for daemon in ${DAEMONS}; do
    sudo service ${daemon} start
done
